name: install

on:
  push:
    tags:
      - "v*"
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "**.py"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "**.py"
  workflow_dispatch:

jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - id: set_tag
        run: |
          is_release=${{ startsWith(github.ref, 'refs/tags/v') }}
          tag=$(git describe --tags --match "v*" ${{ github.ref }} || true)
          if [[ $tag != v* ]]; then
            tag=$(curl -sX GET "https://api.github.com/repos/${{ github.repository }}/releases/latest" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | awk '/tag_name/{print $4}' FS='["]')
            if [[ $tag != v* ]]; then
              tag="v0.0.0"
            fi
            tag=$(date "+$tag-%y%m%d-$(git rev-parse --short HEAD)")
          fi

          # 判断是否为预发布版本（包含 -alpha, -beta, -rc 等标识）
          is_prerelease=false
          if [[ $tag =~ -alpha|-beta|-rc|-ci ]]; then
            is_prerelease=true
          fi

          if ! $($is_release) ; then
            prefix=${tag%-*-*}
            suffix=${tag#$prefix-}
            tag="$prefix-ci.$suffix"
            is_prerelease=true
          fi

          echo tag=$tag | tee -a $GITHUB_OUTPUT
          echo is_release=$is_release | tee -a $GITHUB_OUTPUT
          echo is_prerelease=$is_prerelease | tee -a $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
      is_release: ${{ steps.set_tag.outputs.is_release }}
      is_prerelease: ${{ steps.set_tag.outputs.is_prerelease }}

  prepare-wheels:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - uses: actions/checkout@v6

      - name: Download wheels
        working-directory: ${{ github.workspace }}
        shell: pwsh
        run: |
          python scripts/download_wheels.py `
            --platform win_amd64 `
            --python-version 3.13 `
            --abi cp313 `
            --dest resource/wheels/win-x64

      - uses: actions/upload-artifact@v6
        with:
          name: wheels-win-x64
          path: resource/wheels/win-x64


  install:
    needs: [meta, prepare-wheels]
    strategy:
      # 矩阵分平台构建
      matrix:
        include:
          - os: windows-latest
            platform: win
            arch: x86_64
          - os: windows-latest
            platform: win
            arch: aarch64
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      # 下载 MaaFramework Release
      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MaaFramework
          fileName: "MAA-${{ matrix.platform }}-${{ matrix.arch }}*"
          # 下载指定的 Release Tag
          tag: v5.3.0-beta.5
          out-file-path: "deps"
          extract: true

      # 下载 MFAAvalonia 源码
      - name: Checkout MFAAvalonia source
        uses: actions/checkout@v6
        with:
          repository: SweetSmellFox/MFAAvalonia
          # 使用固定版本
          ref: v2.2.7
          path: MFA-src
          fetch-depth: 1

      # 替换图标文件
      - name: Replace MFAAvalonia icon
        run: |
          cp assets/logo.ico MFA-src/MFAAvalonia/Assets/logo.ico
          echo "已替换 Windows 版 MFAAvalonia 的 logo.ico"

      # 设置 .NET 版本
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      # 编译修改过的 MFAAvalonia
      - name: Build MFAAvaloni
        shell: pwsh
        run: |
          cd MFA-src
          dotnet publish -c Release -r win-${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }} --self-contained true
          cd ..
          New-Item -ItemType Directory -Force -Path MFA | Out-Null
          Copy-Item -Path "MFA-src/bin/AnyCPU/Release/win-${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }}/publish/*" -Destination "MFA" -Recurse -Force

      # 缓存 resource 目录下的所有资源文件,以便后续 Action 运行时可以直接使用缓存的资源文件, 避免重复下载浪费时间和流量
      - name: Cache Resources
        uses: actions/cache@v5
        id: resource-cache-python-embeddable-zip-and-get-pip
        with:
          path: |
            resource/embeddable_python_zip
            resource/get-pip.py
          key: resource-cache-${{ matrix.platform }}-${{ matrix.arch }}-v0.3.0

      # 下载不同系统的 embeddable python zip 包放在 ./resource/embeddable_python_zip 目录下
      - name: Download embeddable Python
        if: steps.resource-cache-python-embeddable-zip-and-get-pip.outputs.cache-hit != 'true'
        shell: bash
        # https://www.python.org/ftp/python/3.13.7/python-3.13.7-embed-amd64.zip
        # https://www.python.org/ftp/python/3.13.7/python-3.13.7-embed-win32.zip
        # https://www.python.org/ftp/python/3.13.7/python-3.13.7-embed-arm64.zip
        run: |
          EMBEDDABLE_PYTHON_DIR="./resource/embeddable_python_zip"
          mkdir -p "${EMBEDDABLE_PYTHON_DIR}"
          if [[ "${{ matrix.platform }}" == "win" ]]; then
            if [[ "${{ matrix.arch }}" == "x86_64" ]]; then
              echo "Downloading embeddable Python for Windows x86_64..."
              PYTHON_URL="https://www.python.org/ftp/python/3.13.7/python-3.13.7-embed-amd64.zip"
            else
              echo "Downloading embeddable Python for Windows ARM64..."
              PYTHON_URL="https://www.python.org/ftp/python/3.13.7/python-3.13.7-embed-arm64.zip"
            fi
            echo "Downloading embeddable Python from ${PYTHON_URL}..."
            curl -L -o "${EMBEDDABLE_PYTHON_DIR}/python-3.13.7-embed-${{ matrix.arch }}.zip" "${PYTHON_URL}"
          else
            echo "便携版Python目前仅支持Windows系统, 对于${{ matrix.platform }}系统将跳过下载步骤."
          fi
          
      # 下载 get-pip.py 到 ./resource/get-pip.py
      - name: Download get-pip.py
        if: steps.resource-cache-python-embeddable-zip-and-get-pip.outputs.cache-hit != 'true'
        shell: bash
        run: |
          curl -L -o ./resource/get-pip.py https://bootstrap.pypa.io/get-pip.py

      # 根据项目 pyproject.toml 下载离线的 Python Wheels 包到 ./resource/wheels 目录下
      # - name: Download Windows Python Wheels
      #   # if: steps.resource-cache.outputs.cache-hit != 'true'
      #   shell: bash
      #   run: |
      #     python scripts/download_wheels.py  --platform win_amd64 --python-version 3.13 --abi cp313 --dest ./resource/wheels  --extra "colorama>=0.4.6"

      - name: Download wheels artifact
        if: matrix.platform == 'win' && matrix.arch == 'x86_64'
        uses: actions/download-artifact@v7
        with:
          name: wheels-win-x64
          path: resource/wheels/win-x64


      - name: Install
        shell: bash
        env:
          PYTHONIOENCODING: utf-8
        # 需要先安装 loguru, 否则 install.py 里面的 logger 会报错
        run: |
          pip install loguru
          python scripts/install.py ${{ needs.meta.outputs.tag }} ${{ matrix.platform }} ${{ matrix.arch }}

          if [[ "${{ matrix.platform }}" != "android" ]]; then
            if [ -d "MFA" ]; then
              echo "Copying MFA files to install directory..."
              mkdir -p install
              if [[ "$RUNNER_OS" == "Windows" ]]; then
                pwsh -Command "Copy-Item -Path MFA/* -Destination install -Recurse -Force"
              else
                rsync -av --ignore-existing MFA/ install/
              fi
            else
              echo "MFA directory not found, skipping copy."
            fi
          else
            echo "Skipping copy MFA for Android."
          fi 

      - uses: actions/upload-artifact@v6
        with:
          name: MaaStarResonance-${{ matrix.platform }}-${{ matrix.arch }}
          path: "install"

  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.generate-changelog.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Generate changelog with Python script
        id: generate-changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 生成最新版本的 changelog
          python scripts/generate_changelog.py --latest > CHANGES.md
          
          # 将内容输出到 GitHub Actions output
          {
            echo 'content<<EOF'
            cat CHANGES.md
            echo EOF
          } >> "$GITHUB_OUTPUT"
          
          echo "✅ Changelog 已生成"

  release:
    if: ${{ needs.meta.outputs.is_release == 'true' }}
    needs: [meta, install, changelog]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          path: assets

      - run: |
          cd assets
          for f in *; do
            (cd $f && zip -r ../$f-${{ needs.meta.outputs.tag }}.zip .)
          done

      - uses: softprops/action-gh-release@v2
        with:
          files: assets/*
          tag_name: ${{ needs.meta.outputs.tag }}
          body: ${{ needs.changelog.outputs.release_body }}
          draft: false
          prerelease: ${{ needs.meta.outputs.is_prerelease == 'true' }}

      - name: Trigger MirrorChyanUploading
        run: |
          gh workflow run --repo $GITHUB_REPOSITORY mirrorchyan
          gh workflow run --repo $GITHUB_REPOSITORY mirrorchyan_release_note
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
